name: Run Scraper and Create release

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Create virtual environment
        run: uv venv

      - name: Install lxml
        run:
          uv pip install lxml

      - name: Run main script
        run: uv run -m main

      - name: Archive output files
        run: |
          tar -czvf kubernetes-docs-output.tar.gz ./output

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-docs-artifacts
          path: kubernetes-docs-output.tar.gz

      - name: Generate timestamp for release
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.sha }}
          name: Kubernetes Docs Automated Release ${{ steps.timestamp.outputs.timestamp }}
          draft: true
          generate_release_notes: false
          files: kubernetes-docs-output.tar.gz

