name: Run Scraper and Create release

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Create virtual environment
        run: uv venv

      - name: Install lxml
        run: |
          uv pip install lxml
          uv pip install lxml[html_clean]

      - name: Run main script
        run: uv run -m main

      - name: Archive docs
        run: |
          tar -czvf docs.tar.gz --exclude=./docs/extras ./extras

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs.tar.gz

      - name: Archive extras
        run: |
          tar -czvf extras.tar.gz ./docs/extras

      - name: Upload extras
        uses: actions/upload-artifact@v4
        with:
          name: extras
          path: extras.tar.gz

      - name: Generate timestamp for release
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.sha }}
          name: Kubernetes Docs Automated Release ${{ steps.timestamp.outputs.timestamp }}
          draft: true
          generate_release_notes: false
          files:
            docs.tar.gz
            extras.tar.gz

